### ISSUE TITLE
generate_met_files_arrow function gives all 0 Rain values

### ISSUE THREAD

**Issue by melofton** [FLARE-forecast/FLAREr#79]
@rqthomas the issue is this ifelse statement:
`Rain = ifelse(use_ler_vars, Rain * (60 * 60), Rain * (60 * 60 * 24)/1000),`
but I am not sure why? (I set use_ler_vars to FALSE)
`Rain = Rain * (60 * 60 * 24)/1000`
to generate met files for GLM-AED works fine

**Comment by rqthomas** [comment]
Thanks @melofton I tracked down and fixed the issue.
